### ISSUE TITLE
Lacking decryption error handling

### ISSUE THREAD

**Issue by HQJaTu** [stymiee/php-simple-encryption#6]
As an example, in `trait DecryptNoIV` there is a simple nested `openssl_decrypt()` into `rtrim()`.

What if decryption fails?
You cannot `rtrim()` a boolean or null.

**Comment by stymiee** [comment]
Good catch. I am releasing 1.0.5 today to throw an exception if decryption fails for any reason.

**Comment by stymiee** [comment]
1.0.5 has been released. Thank you for submitting this issue.

**Comment by leensky1027** [comment]
Hi, jari, I don't how I will message personally, i juat want your help about using the Firmware Mod Kit in windows. please
